### ISSUE TITLE
Improve exception handling

### ISSUE THREAD

**Issue by iMicknl** [iMicknl/ha-nest-protect#34]
### The problem

Since this integration is still work in progress, I didn't add good error handling / retry logic yet. This will need to be added to make sure the integration is reliable and will always receive state updates.

### What version of this integration (ha-nest-protect) has the issue?

0.3.0

### What version of Home Assistant Core has the issue?

2022.2.0

### Home Assistant log

<details><summary>Logs</summary>

```
2022-03-10 04:13:14 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/nest_protect/__init__.py", line 123, in _async_subscribe_for_data
result = await entry_data.client.subscribe_for_data(
File "/config/custom_components/nest_protect/pynest/client.py", line 222, in subscribe_for_data
raise NotAuthenticatedException(await response.text())
custom_components.nest_protect.pynest.exceptions.NotAuthenticatedException
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/config/custom_components/nest_protect/__init__.py", line 170, in _async_subscribe_for_data
await entry_data.client.authenticate(entry_data.client.auth.access_token)
File "/config/custom_components/nest_protect/pynest/client.py", line 160, in authenticate
nest_response = await response.json()
File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1103, in json
raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('https://home.nest.com/session')
```

</details>

**Comment by iMicknl** [comment]
```
2022-03-11 03:13:54 ERROR (MainThread) [custom_components.nest_protect] Subscriber: pynest exception.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/pynest/client.py", line 225, in subscribe_for_data
    result = await response.json()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://czfe39-front01-iad01.transport.home.nest.com/v6/subscribe')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 123, in _async_subscribe_for_data
    result = await entry_data.client.subscribe_for_data(
  File "/config/custom_components/nest_protect/pynest/client.py", line 229, in subscribe_for_data
    raise PynestException(
custom_components.nest_protect.pynest.exceptions.PynestException: 504 error while subscribing - <html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.10.3</center>
</body>
</html>
```

**Comment by Daneish** [comment]
Nice! With debug on I can see that the integration is recovering from the 504 error:
````2022-03-14 21:38:41 DEBUG (MainThread) [custom_components.nest_protect] Subscriber: listening for new data
2022-03-14 21:42:41 DEBUG (MainThread) [custom_components.nest_protect] Subscriber: listening for new data
2022-03-14 22:48:44 ERROR (MainThread) [custom_components.nest_protect] Subscriber: pynest exception.
Traceback (most recent call last):
File "/config/custom_components/nest_protect/pynest/client.py", line 238, in subscribe_for_data
result = await response.json()
File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1103, in json
raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://czfe55-front01-iad01.transport.home.nest.com/v6/subscribe')
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/config/custom_components/nest_protect/__init__.py", line 128, in _async_subscribe_for_data
result = await entry_data.client.subscribe_for_data(
File "/config/custom_components/nest_protect/pynest/client.py", line 242, in subscribe_for_data
raise PynestException(
custom_components.nest_protect.pynest.exceptions.PynestException: 504 error while subscribing - <html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.10.3</center>
</body>
</html>
2022-03-14 22:49:44 DEBUG (MainThread) [custom_components.nest_protect] Subscriber: listening for new data
2022-03-14 22:49:44 DEBUG (MainThread) [custom_components.nest_protect] Subscriber: retrieving new Google access token
2022-03-14 22:52:42 ERROR (MainThread) [custom_components.nest_protect] Subscriber: pynest exception.
Traceback (most recent call last):
File "/config/custom_components/nest_protect/pynest/client.py", line 238, in subscribe_for_data
result = await response.json()
File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1103, in json
raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://czfe75-front01-iad01.transport.home.nest.com/v6/subscribe')
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/config/custom_components/nest_protect/__init__.py", line 128, in _async_subscribe_for_data
result = await entry_data.client.subscribe_for_data(
File "/config/custom_components/nest_protect/pynest/client.py", line 242, in subscribe_for_data
raise PynestException(
custom_components.nest_protect.pynest.exceptions.PynestException: 504 error while subscribing - <html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.10.3</center>
</body>
</html>
2022-03-14 22:53:42 DEBUG (MainThread) [custom_components.nest_protect] Subscriber: listening for new data
2022-03-14 23:51:40 DEBUG (MainThread) [custom_components.nest_protect] Subscriber: listening for new data
2022-03-14 23:51:40 DEBUG (MainThread) [custom_components.nest_protect] Subscriber: retrieving new Google access token
2022-03-14 23:51:40 DEBUG (MainThread) [custom_components.nest_protect] Subscriber: listening for new data
2022-03-14 23:51:40 DEBUG (MainThread) [custom_components.nest_protect] Subscriber: retrieving new Google access token

**Comment by iMicknl** [comment]
@Daneish which version do you currently run? I would need to double check, but in the last version, a 504 error should not throw an ugly exception like this anymore.

**Comment by Daneish** [comment]
I'm running v0.3.2, but I can see 0.3.3 is now out, so can jump on that and test if you like?

**Comment by iMicknl** [comment]
> I'm running v0.3.2, but I can see 0.3.3 is now out, so can jump on that and test if you like?

0.3.3 should solve the 504 exception. However, the subscriber still needs some additional love.

**Comment by Daneish** [comment]
Can confirm, after updating to 0.3.3 I haven’t had any more exceptions, but with Debug on I can see that its still getting a bunch of timeouts:
`DEBUG (MainThread) [custom_components.nest_protect] Subscriber: gateway time-out. Pausing for 2 minutes.`

**Comment by brooksben11** [comment]
First off, THANK YOU for working on this.

Just set this up yesterday and it works great, HOWEVER I noticed this morning that the occupancy sensors weren't changing state (some were clear, others detected). I have my router restart every morning at 3am and I noticed that none of them changed state after that time; I'm guessing it timed out since it couldn't reach the interwebs for the 5+ minutes it takes my router to restart. A restart of HA had everything working fine again. I installed the latest version of the integration yesterday and as of last evening HA was fully updated. Let me know if you need any additional info!

**Comment by brooksben11** [comment]
Here's what I got this morning:
2022-03-18 02:22:49 DEBUG (MainThread) [custom_components.nest_protect] Subscriber: retrieving new Google access token
2022-03-18 02:24:52 DEBUG (MainThread) [custom_components.nest_protect] Subscriber: listening for new data
2022-03-18 02:25:07 DEBUG (MainThread) [custom_components.nest_protect] Subscriber: listening for new data
2022-03-18 02:25:14 DEBUG (MainThread) [custom_components.nest_protect] Subscriber: listening for new data
2022-03-18 02:32:04 DEBUG (MainThread) [custom_components.nest_protect] Subscriber: listening for new data
2022-03-18 02:33:10 DEBUG (MainThread) [custom_components.nest_protect] Subscriber: listening for new data
2022-03-18 02:33:49 DEBUG (MainThread) [custom_components.nest_protect] Subscriber: listening for new data
2022-03-18 02:34:03 DEBUG (MainThread) [custom_components.nest_protect] Subscriber: listening for new data
2022-03-18 02:34:20 DEBUG (MainThread) [custom_components.nest_protect] Subscriber: listening for new data
2022-03-18 02:35:08 DEBUG (MainThread) [custom_components.nest_protect] Subscriber: listening for new data
2022-03-18 02:35:14 DEBUG (MainThread) [custom_components.nest_protect] Subscriber: listening for new data
2022-03-18 02:36:03 DEBUG (MainThread) [custom_components.nest_protect] Subscriber: listening for new data
2022-03-18 02:47:26 DEBUG (MainThread) [custom_components.nest_protect] Subscriber: listening for new data
2022-03-18 02:47:37 DEBUG (MainThread) [custom_components.nest_protect] Subscriber: listening for new data
2022-03-18 02:47:55 DEBUG (MainThread) [custom_components.nest_protect] Subscriber: listening for new data
2022-03-18 02:47:57 DEBUG (MainThread) [custom_components.nest_protect] Subscriber: listening for new data
2022-03-18 02:52:49 DEBUG (MainThread) [custom_components.nest_protect] Subscriber: listening for new data
2022-03-18 03:00:08 DEBUG (MainThread) [custom_components.nest_protect] Subscriber: listening for new data

Nothing terribly enlightening it seems, it just stops at 3am when my router resets.

**Comment by iMicknl** [comment]
Is there no message / error afterwards?

**Comment by brooksben11** [comment]
Correct, nothing at all from the last entry at 3am until about 15 minutes ago when I pulled it.

**Comment by iMicknl** [comment]
@brooksben11 let's track this in a new issue, since I fixed most of the issues in this issue. Could you create a new issue (with also some steps to reproduce). I will try to have a look in the coming weeks.
